name: Keep develop updated
on:
  push:
    branches:
      - release/*
      - master
jobs:
  releaseToDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Reset branch
        run: |
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
          git reset --hard ${{ steps.extract_branch.outputs.branch }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Merge ${{ steps.extract_branch.outputs.branch }} to develop
          labels: M, automated-pr
          branch-suffix: timestamp
