name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Setup React Native environment
        run: |
          yarn add react-native@0.63.4
          yarn add react@16.13.1
      - name: Run tests
        run: yarn test
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
