name: publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - react_version: '16.9.0'
            react_native_version: '0.61.5'
            metro_babel_preset_version: '0.56.0'
          - react_version: '17.0.1'
            react_native_version: '0.64.2'
            metro_babel_preset_version: '0.64.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Setup React Native environment
        run: |
          yarn add react@${{ matrix.react_version }}
          yarn add react-native@${{ matrix.react_native_version }}
          yarn add metro-react-native-babel-preset@${{ matrix.metro_babel_preset_version }}

      - name: Run tests
        run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
